# Generated by Django 4.1.3 on 2023-05-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmt', '0003_remove_studyingprograms_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyingprograms',
            name='budgetPlaces',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='ege',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='formOfEdu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='greenWave',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='passingScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='priceDL',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='priceFT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='pricePT',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='profile',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='spo',
            field=models.TextField(),
        ),
    ]
