# Generated by Django 4.1.3 on 2023-05-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmt', '0009_alter_magistracy_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyingprograms',
            name='greenWave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Зеленая волна'),
        ),
    ]
