# Generated by Django 4.1.3 on 2023-06-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmt', '0010_alter_studyingprograms_greenwave'),
    ]

    operations = [
        migrations.AddField(
            model_name='magistracy',
            name='budgetPlaces',
            field=models.IntegerField(blank=True, null=True, verbose_name='Бюджетные места'),
        ),
        migrations.AddField(
            model_name='magistracy',
            name='exam',
            field=models.TextField(blank=True, null=True, verbose_name='Вступительный экзамен'),
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='egeOptionally',
            field=models.TextField(blank=True, verbose_name='ЕГЭ По выбору'),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='budgetPlaces',
            field=models.TextField(blank=True, null=True, verbose_name='Бюджетные места'),
        ),
        migrations.AlterField(
            model_name='studyingprograms',
            name='passingScore',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проходной балл'),
        ),
    ]
