# Generated by Django 4.1.3 on 2023-05-18 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyingprograms',
            name='budgetPlaces',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='ege',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='greenWave',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='passingScore',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='price',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='studyingprograms',
            name='spo',
            field=models.TextField(blank=True),
        ),
    ]
