# Generated by Django 4.1.3 on 2023-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mkmt', '0006_magistracy_trainingperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magistracy',
            name='priceDL',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость заочного обучения'),
        ),
        migrations.AlterField(
            model_name='magistracy',
            name='priceFT',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость очного обучения'),
        ),
        migrations.AlterField(
            model_name='magistracy',
            name='pricePT',
            field=models.TextField(blank=True, null=True, verbose_name='Стоимость очно-заочного обучения'),
        ),
    ]
